# Generated by Django 4.2 on 2023-05-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gridder', '0002_rename_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
