# Generated by Django 4.2 on 2023-05-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gridder', '0003_profile_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.TextField()),
                ('poll_code', models.TextField()),
                ('poll_author', models.TextField()),
                ('appended_document', models.FileField(default='empty', upload_to='documents')),
                ('fields', models.JSONField()),
            ],
        ),
    ]
