# Generated by Django 4.2 on 2023-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gridder', '0004_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='appended_document',
            field=models.FileField(default='sampledoc.docx', upload_to='documents'),
        ),
    ]
