# Generated by Django 4.2 on 2023-05-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gridder', '0005_alter_poll_appended_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_code', models.TextField()),
                ('field_values', models.JSONField()),
            ],
        ),
    ]
