# Generated by Django 4.2 on 2023-05-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gridder', '0006_pollvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='document_name',
            field=models.TextField(default='document_name'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_author',
            field=models.TextField(default='appended_document'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_code',
            field=models.TextField(default='poll_code'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_name',
            field=models.TextField(default='poll_name'),
        ),
    ]
