# Generated by Django 4.2 on 2023-05-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_gridder', '0007_poll_document_name_alter_poll_poll_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='document_name',
            new_name='original_doc_name',
        ),
    ]
