# Generated by Django 4.2 on 2023-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gridder', '0008_rename_document_name_poll_original_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='original_doc_name',
            field=models.TextField(blank=True, default='document_name'),
        ),
    ]
