# Generated by Django 4.2 on 2023-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gridder', '0009_alter_poll_original_doc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollvalue',
            name='user_name',
            field=models.TextField(default='none'),
        ),
    ]
