# Generated by Django 4.2 on 2023-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gridder', '0010_pollvalue_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollvalue',
            name='poll_name',
            field=models.TextField(default='none'),
        ),
    ]
